name: flappybird
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flame: ^0.26.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/0.png
    - assets/images/1.png
    - assets/images/2.png
    - assets/images/3.png
    - assets/images/4.png
    - assets/images/5.png
    - assets/images/6.png
    - assets/images/7.png
    - assets/images/8.png
    - assets/images/9.png
    - assets/images/background-day.png
    - assets/images/background-night.png
    - assets/images/base.png
    - assets/images/bluebird-downflap.png
    - assets/images/bluebird-midflap.png
    - assets/images/bluebird-upflap.png
    - assets/images/gameover.png
    - assets/images/message.png
    - assets/images/pipe-green.png
    - assets/images/pipe-red.png
    - assets/images/redbird-downflap.png
    - assets/images/redbird-midflap.png
    - assets/images/redbird-upflap.png
    - assets/images/yellowbird-downflap.png
    - assets/images/yellowbird-midflap.png
    - assets/images/yellowbird-upflap.png
